### ISSUE TITLE
GitHub Preview

### ISSUE THREAD

**Issue by Tereseus** [ExCurio/Codecademy_WebCourse_DasmotosArtsCrafts#1]
Good job setting up your project repo to make GitHub preview work correctly. I don't know if you know that you did this, but it is something not even 10% of users do. There is a slight issue with the pathing of your CSS file so the styling is not apparent. Good job though.

**Comment by ExCurio** [comment]
The pathing issue is because I wasn't aware that the directory structure should accompany the project to GitHub and this was before I learned to use Git on my laptop. 
Thanks,
-Keith
