### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Tereseus** [ExCurio/Codecademy_WebCourse_DasmotosArtsCrafts#2]
### Criteria 1: HTML and CSS Linking
* **Score Level**: 2/4 (Needs some work)
* _Comment(s)_:  Unfortunately even though you did use relative pathing to enable linking your CSS in your HTML, the pathing is incorrect. Here is a hint, you do not have the same file structure on your GitHub as you do on your computer, look for the resource folder etc..  You did however load your images correctly.  Great work.

### Criteria 2: Implementation of Design Specification and Content
* **Score Level**: 4/4 (Exceeds Expectations)
* _Comment(s)_: Your page includes all styles and content provided in the design specification.  Nice work!

### Criteria 3: HTML Tags and Content
* **Score Level**: 4/4 (Exceeds Expectations)
* _Comment(s)_: Your HTML content matches the design specification.  Everything is present from the header to the appropriate sections.  You also use elements according to their semantic meaning when displaying the different types of content on the page, which is awesome!  Awesome job!

### Criteria 4: Use of CSS Selectors and Syntax
* **Score Level**: 4/4 (Exceeds Expectations)
* _Comment(s)_: You did well when choosing your CSS selectors.  You gave them descriptive names, which also enhances the readability of the code.  Additionally, great work leveraging inheritance and setting shared styles on a top-level selector such as the body.  This really helps keep your code "DRY."  Great job!

+1 GitHub Preview

### Overall Score: 15/16
Overall, you did a great job with this project. Your formatting was great, making all of code easy to read. You demonstrated good knowledge of both HTML and CSS - using semantic elements appropriately in the HTML and leveraging inheritance to keep your CSS "DRY." You built your project to meet all of the specs and it shows in the final product, there is however one small issue with the linking of your CSS file to your HTML. Fix that and it will be perfect. Great job!

**Comment by ExCurio** [comment]
Resource linking: I did not realize that I needed to copy the directory structure to GitHub. In fact I wasn't aware that GitHub supported it. Now that I have Git installed on my laptop, keeping the repositories in sync will be much easier. Thank you for the feedback and kind words.
-Keith
